### ISSUE TITLE
README example panics

### ISSUE THREAD

**Issue by sewnie** [jwijenbergh/puregotk#3]
```
$ PUREGOTK_LIBNAME_PATH=/usr/lib/libgtk-4.so ./pure
SIGSEGV: segmentation violation
PC=0x7f3e9e19e642 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x4805c0, 0xc0004cbc00)
        /usr/lib/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00012d598 sp=0xc00012d560 pc=0x4059eb
github.com/jwijenbergh/purego.RegisterFunc.func1({0xc00009c050?, 0x3?, 0x3?})
        /home/meow/.cache/go/mod/github.com/jwijenbergh/purego@v0.0.0-20240105094719-439893e0402d/func.go:253 +0xc65 fp=0xc00012d980 sp=0xc00012d598 pc=0x47f125
reflect.callReflect(0xc000387740, 0xc00012dee0, 0xc00012ddb8, 0xc00012ddc0)
        /usr/lib/go/src/reflect/value.go:782 +0x54b fp=0xc00012dd68 sp=0xc00012d980 pc=0x47916b
reflect.callReflect(0xc000387740, 0xc00012dee0, 0xc00012ddb8, 0xc00012ddc0)
        <autogenerated>:1 +0x45 fp=0xc00012dd98 sp=0xc00012dd68 pc=0x47db85
reflect.makeFuncStub()
        /usr/lib/go/src/reflect/asm_amd64.s:47 +0x6e fp=0xc00012dee0 sp=0xc00012dd98 pc=0x47d62e
github.com/jwijenbergh/puregotk/v4/gio.(*Application).Run(...)
        /home/meow/.cache/go/mod/github.com/jwijenbergh/puregotk@v0.0.0-20240108164743-387c6c77b6a0/v4/gio/gapplication.go:669
main.main()
        /home/meow/src/tmp/cmd/pure/main.go:16 +0xd2 fp=0xc00012df40 sp=0xc00012dee0 pc=0x50eed2
runtime.main()
        /usr/lib/go/src/runtime/proc.go:267 +0x2bb fp=0xc00012dfe0 sp=0xc00012df40 pc=0x43765b
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00012dfe8 sp=0xc00012dfe0 pc=0x464bc1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000064fa8 sp=0xc000064f88 pc=0x437aae
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.forcegchelper()
        /usr/lib/go/src/runtime/proc.go:322 +0xb3 fp=0xc000064fe0 sp=0xc000064fa8 pc=0x437933
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000064fe8 sp=0xc000064fe0 pc=0x464bc1
created by runtime.init.6 in goroutine 1
        /usr/lib/go/src/runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000065778 sp=0xc000065758 pc=0x437aae
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /usr/lib/go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc0000657c8 sp=0xc000065778 pc=0x42417f
runtime.gcenable.func1()
        /usr/lib/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000657e0 sp=0xc0000657c8 pc=0x4192e5
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000657e8 sp=0xc0000657e0 pc=0x464bc1
created by runtime.gcenable in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007e000?, 0x6349e8?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000065f70 sp=0xc000065f50 pc=0x437aae
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x70bd80)
        /usr/lib/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc000065fa0 sp=0xc000065f70 pc=0x421a09
runtime.bgscavenge(0x0?)
        /usr/lib/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc000065fc8 sp=0xc000065fa0 pc=0x421fb9
runtime.gcenable.func2()
        /usr/lib/go/src/runtime/mgc.go:201 +0x25 fp=0xc000065fe0 sp=0xc000065fc8 pc=0x419285
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x464bc1
created by runtime.gcenable in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:201 +0xa5

goroutine 18 [finalizer wait]:
runtime.gopark(0x198?, 0x5d2dc0?, 0x1?, 0x8c?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000064620 sp=0xc000064600 pc=0x437aae
runtime.runfinq()
        /usr/lib/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000647e0 sp=0xc000064620 pc=0x418307
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000647e8 sp=0xc0000647e0 pc=0x464bc1
created by runtime.createfing in goroutine 1
        /usr/lib/go/src/runtime/mfinal.go:163 +0x3d

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000060750 sp=0xc000060730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000607e0 sp=0xc000060750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000066750 sp=0xc000066730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000667e0 sp=0xc000066750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000667e8 sp=0xc0000667e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000066f50 sp=0xc000066f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000066fe0 sp=0xc000066f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000067750 sp=0xc000067730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000677e0 sp=0xc000067750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000677e8 sp=0xc0000677e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000067f50 sp=0xc000067f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000067fe0 sp=0xc000067f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a4750 sp=0xc0000a4730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a47e0 sp=0xc0000a4750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a47e8 sp=0xc0000a47e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a4f50 sp=0xc0000a4f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a4fe0 sp=0xc0000a4f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a4fe8 sp=0xc0000a4fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000060f50 sp=0xc000060f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000060fe0 sp=0xc000060f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a0750 sp=0xc0000a0730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a07e0 sp=0xc0000a0750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a07e8 sp=0xc0000a07e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 35 [GC worker (idle)]:
runtime.gopark(0xdfdf4fc96e9?, 0x3?, 0x37?, 0xf3?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a0f50 sp=0xc0000a0f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a0fe0 sp=0xc0000a0f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a0fe8 sp=0xc0000a0fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 36 [GC worker (idle)]:
runtime.gopark(0xdfdf4fbdbf4?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a1750 sp=0xc0000a1730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a17e0 sp=0xc0000a1750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a17e8 sp=0xc0000a17e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 37 [GC worker (idle)]:
runtime.gopark(0xdfdf4fbd7fd?, 0x3?, 0x45?, 0x12?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a1f50 sp=0xc0000a1f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a1fe0 sp=0xc0000a1f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a1fe8 sp=0xc0000a1fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x745ea0?, 0x1?, 0x83?, 0x35?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a2750 sp=0xc0000a2730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a27e0 sp=0xc0000a2750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a27e8 sp=0xc0000a27e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 39 [GC worker (idle)]:
runtime.gopark(0xdfdf4fbd9cd?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a2f50 sp=0xc0000a2f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a2fe0 sp=0xc0000a2f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a2fe8 sp=0xc0000a2fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 40 [GC worker (idle)]:
runtime.gopark(0xdfdf4fbd536?, 0x1?, 0x1?, 0xb?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a3750 sp=0xc0000a3730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a37e0 sp=0xc0000a3750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a37e8 sp=0xc0000a37e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 41 [GC worker (idle)]:
runtime.gopark(0xdfdf4fb68fc?, 0x1?, 0xeb?, 0x84?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0000a3f50 sp=0xc0000a3f30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000a3fe0 sp=0xc0000a3f50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000a3fe8 sp=0xc0000a3fe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 42 [GC worker (idle)]:
runtime.gopark(0xdfdf4fbd839?, 0x1?, 0x5a?, 0xf1?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00050a750 sp=0xc00050a730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc00050a7e0 sp=0xc00050a750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00050a7e8 sp=0xc00050a7e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 43 [GC worker (idle)]:
runtime.gopark(0xdfdf4fbd967?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00050af50 sp=0xc00050af30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc00050afe0 sp=0xc00050af50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00050afe8 sp=0xc00050afe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 44 [GC worker (idle)]:
runtime.gopark(0x745ea0?, 0x1?, 0xc4?, 0x37?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00050b750 sp=0xc00050b730 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc00050b7e0 sp=0xc00050b750 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00050b7e8 sp=0xc00050b7e0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 45 [GC worker (idle)]:
runtime.gopark(0x745ea0?, 0x1?, 0x30?, 0xaf?, 0x0?)
        /usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00050bf50 sp=0xc00050bf30 pc=0x437aae
runtime.gcBgMarkWorker()
        /usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc00050bfe0 sp=0xc00050bf50 pc=0x41ae65
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00050bfe8 sp=0xc00050bfe0 pc=0x464bc1
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/lib/go/src/runtime/mgc.go:1219 +0x1c

rax    0x0
rbx    0x0
rcx    0x1
rdx    0x10
rdi    0x0
rsi    0x2f
rbp    0x2f
rsp    0x7ffd491cc318
r8     0xfefefefefefefeff
r9     0x7f3e5577fa75
r10    0x7ffd491cefe7
r11    0x0
r12    0x7f3e9e221df8
r13    0x3f8
r14    0x7ffd491cd530
r15    0x3f8
rip    0x7f3e9e19e642
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by jwijenbergh** [comment]
> PUREGOTK_LIBNAME_PATH

this is incorrect. LIBNAME should be the name of the lib, e.g. PUREGOTK_GTK_PATH. PUREGOTK_LIB_FOLDER is probably what you're looking for. But still weird that it panics, which distro?

**Comment by apprehensions** [comment]
Setting `CGO_ENABLED` to either `1` or `0` produces the same result. I use my own distribution of gtk and libadwaita i packed by hand.

**Comment by jwijenbergh** [comment]
> Setting `CGO_ENABLED` to either `1` or `0` produces the same result. I use my own distribution of gtk and libadwaita i packed by hand.

I need some way to reproduce it :)

**Comment by apprehensions** [comment]
`gotk4` works fine. libadwaita `1.4.2-1` and gtk4 `4.13.3-2`, i *shouldnt* need to set env var as the libraries are present in `/usr/lib64`.

**Comment by jwijenbergh** [comment]
> gotk4 works fine

gotk4 uses headers, not shared library files.

 > https://github.com/ehawkvu/kiss-xorg/blob/422a41d4d1199457b4b9340fba15150d352ae1f5/community/gtk%2B4/build
> https://github.com/ehawkvu/kiss-xorg/blob/422a41d4d1199457b4b9340fba15150d352ae1f5/community/libadwaita/build

Ah so kiss linux, I will try to set up a vm when I have the time

**Comment by apprehensions** [comment]
> Ah so kiss linux

Please don't. I will try to run the example on my Alpine laptop.

**Comment by jwijenbergh** [comment]
> Please don't

Hahaha, I figured it would take some time :)

> I will try to run the example on my Alpine laptop

Okay thank you

**Comment by apprehensions** [comment]
I face this same issue on a Chimera system. I had to set `PUREGOTK_LIB_FOLDER` to `/usr/lib` because `/usr/lib64` is not present.

```
$ PUREGOTK_LIB_FOLDER=/usr/lib ./pure                   
SIGSEGV: segmentation violation
PC=0x7f30cdeaf820 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4805c0, 0xc000437dc0)
        /usr/lib/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00049a230 sp=0xc00049a1f8 pc=0x4059eb
github.com/jwijenbergh/purego.RegisterFunc.func1({0xc0004ac768?, 0x1?, 0x1?})
        /home/meow/.cache/go/mod/github.com/jwijenbergh/purego@v0.0.0-20240105094719-439893e0402d/func.go:253 +0xc65 fp=0xc00049a618 sp=0xc00049a230 pc=0x47f125
reflect.callReflect(0xc0002a7350, 0xc00049ab78, 0xc00049aa50, 0xc00049aa58)
        /usr/lib/go/src/reflect/value.go:782 +0x54b fp=0xc00049aa00 sp=0xc00049a618 pc=0x47916b
reflect.callReflect(0xc0002a7350, 0xc00049ab78, 0xc00049aa50, 0xc00049aa58)
        <autogenerated>:1 +0x45 fp=0xc00049aa30 sp=0xc00049aa00 pc=0x47db85
reflect.makeFuncStub()
        /usr/lib/go/src/reflect/asm_amd64.s:47 +0x6e fp=0xc00049ab78 sp=0xc00049aa30 pc=0x47d62e
<...>
```
```
gtk4-4.12.3-r0 x86_64 {gtk4} (LGPL-2.1-or-later) [installed]
libadwaita-1.4.0-r1 x86_64 {libadwaita} (LGPL-2.1-or-later) [installed]
```

**Comment by apprehensions** [comment]
Maybe this could be related to `musl`?

**Comment by jwijenbergh** [comment]
Good guess! Could you try a simple purego example? https://github.com/ebitengine/purego#example

**Comment by apprehensions** [comment]
```
$ CGO_ENABLED=0 go run .       
Calling C from Go without Cgo!
$ CGO_ENABLED=1 go run . 
Calling C from Go without Cgo!
```

**Comment by jwijenbergh** [comment]
minimal repro without this lib and only purego (make sure to obtain the newest purego 0.6 alpha):

```go
package main

import (
	"os"

	"github.com/ebitengine/purego"
)

var GtkNewApplication func(string, int) uintptr
var GSignalConnectData func(uintptr, string, uintptr, uintptr, uintptr, int) uint32
var GApplicationRun func(uintptr, int, uintptr) int
var GtkNewApplicationWindow func(uintptr) uintptr
var GtkWindowPresent func(uintptr)

func load() {
	libp := os.Getenv("PUREGOTK_GTK_PATH")
	if libp == "" {
		libp = "/usr/lib/libgtk-4.so"
	}
	libgtk, err := purego.Dlopen(libp, purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}
	purego.RegisterLibFunc(&GtkNewApplication, libgtk, "gtk_application_new")
	purego.RegisterLibFunc(&GSignalConnectData, libgtk, "g_signal_connect_data")
	purego.RegisterLibFunc(&GApplicationRun, libgtk, "g_application_run")
	purego.RegisterLibFunc(&GtkNewApplicationWindow, libgtk, "gtk_application_window_new")
	purego.RegisterLibFunc(&GtkWindowPresent, libgtk, "gtk_window_present")
}

func main() {
	load()
	
	app := GtkNewApplication("com.github.jwijenbergh.puregotk.gtk4.hello", 0)
	GSignalConnectData(app, "activate", purego.NewCallback(func(_ uintptr) {
		w := GtkNewApplicationWindow(app)
		GtkWindowPresent(w)
	}), 0, 0,  0)
	GApplicationRun(app, 0, 0)
}
```

it crashes in GtkWindowPresent (or GtkWindowShow, the example in the README still uses show but it doesn't matter). This doesn't happen on nixos/ubuntu/fedora. Not sure what the issue is

**Comment by jwijenbergh** [comment]
could you try with GSK_RENDERER=cairo, then it works strangely

**Comment by apprehensions** [comment]
same segfault

**Comment by jwijenbergh** [comment]
works fine on chimera linux for me.
![image](https://github.com/jwijenbergh/puregotk/assets/46386452/6a4fbc42-0d8e-4a5a-b94c-ee9fbc2a80b8)

I think the renderer fallback doesn't work correctly for some reason, as when I run it through python I get:

![image](https://github.com/jwijenbergh/puregotk/assets/46386452/b1762c92-d8dd-40de-9363-e9be4af349cc)

**Comment by apprehensions** [comment]
Can no longer reproduce this issue on Alpine.
Needs command line `PUREGOTK_LIB_FOLDER=/usr/lib ./demo`, #7

**Comment by jwijenbergh** [comment]
let me know if still a problem
